spec:
  replicas: 3
  selector:
    matchLabels:
      app: fishnet-alpine
  template:
    metadata:
      name: fishnet-alpine
      labels:
        app: fishnet-alpine
    spec:
      containers:
        - name: fishnet-alpine
          image: harbor.fn-k8s.fishnet.com:32022/fishnet/alpine
          imagePullPolicy: IfNotPresent
          command: ["sleep","60000"]
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always